package com.entity;


import lombok.Data;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.time.LocalDate;

@Entity
@NoArgsConstructor // we must have no args constructor when we use the @Entity
// we can't have all args constructor because id is generated by postgres
@Data

@Table(name="books")
public class Book {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    Long id;
    String title;
    String author;
    @Column(columnDefinition = "DATE") //type date is in postgres
    LocalDate datePublished;

    public Book(String title, String author, LocalDate datePublished) {
        this.title = title;
        this.author = author;
        this.datePublished = datePublished;
    }
}
